## Parcial No. 2 Bases de Datos  

    Universidad del Valle de Guatemala
    Bases de Datos
    Bidkar Pojoy
                                                                                            Jorge Eduardo Suchite Martinez
                                                                                             Carnet 15293
                                                                                             Mayo 30, de 2019

### Parte I Conceptos Teóricos 

Desarrolle / resuelva / conteste los siguientes enunciados

a)¿Qué es una base de datos?
b)Proceso de Normalización
c)¿Cuál es el objetivo principal de la Inteligencia de Negocios? ¿Cómo se relaciona este concepto con el concepto de DataWareHouse?

### a)  ¿Qué es una base de datos?

Una Base de datos surge con el fin de ayudar al almacenamiento de información en la cual todo dato está relacionado en un mismo contexto. Además, trata de que esta información sea lo más entendible posible y al igual que su extracción. 



Las bases de datos como tal, surgieron con el fin de almacenar información de ventas, compras y todo lo que se tuviera que tener registro de todo lo importante ya sea de información personal o de su información monetarioa. 


Todo con fines de negocio y comercialización en un mundo globalizado e interconectado.

Además, una base de datos está conformada por un:

Hardaware:  que sería uno o varios discos de estado solido de gran potencia
Software:  Es el servicio o plataforma de que se encarga del entorno de la base de datos en sí para que la información y
el usuario interactúe.


Administrador o Ingeniero en Ciencias de la Computación: es el encargado de velar por la integridad de la base de datos. (Parte importante puesto que es información valiosa para alguien la que está almacenada en ese lugar y tiene que ver alguien para que el usuario no cometa errores o se roben la información. s

### b) Proceso de Normalización

Sabemos que, en muchas de las compañias las bases de datos no están del todo correctas al momento de diseñarlas puesto que, en las épocas anteriores. Las personas solo necesitaban cierta información y solo la ponían y/o configuraban la db en base a que todo estuviera en una tabla. Lo cual no tenía ninguna conección o fluidez al momento de sacar información o se redundaba la información. o no se actualizaba en su totalidad al momento de insertar nueva información

Por esto mismo, se creo la normalización de una bases de datos en la cual se puede realizar una mejor práctica de creación de bases de datos y evitar lo antes mencionado. 

Entidad-Relación: se creo este concepto con el fin de que también se puedera ver qué recorrido hacía la información en la base de datos al igual que puede ser una forma gráfica de normalización.

Existen 4 niveles para realizar el proceso de Normalización. Pero por cuestiones de tiempo solo serán nombradas y no explicadas [F1N, F2N, F3N y F4N]

### c) ¿Cuál es el objetivo principal de la Inteligencia de Negocios? ¿Cómo se relaciona este concepto con el concepto de DataWareHouse?

1. A grandes rasgos es la forma, herramienta o medio en la cuál se obtienen datos o información de los procesos empresariales al igual de todo lo que conlleva las jerarquías y eslavones de la empresa (gestión empresarial) para poder  darles una interpretación o análisis  para poder optimizar ya sea un proceso o la rentabilidad de los servicios/productos que la empresa tiene o provee. 




2. El concepto de DataWareHouse es demasiado amplio, pero para fines de esta ocasión se resume en lo siguiente:
   
Se podría decir que un DataWareHouse s como un repositorio de Github en el cual está creado con el propósito de recabar información de diferentes fuentes de un negocio o de una empresa en este caso con el fin de optener análisis de cierto grupo de información y poer concluir o recomendar en base a estos resultados obtenidos por el DataWareHouse. 
   
Estaría relacionado puesto que con la inteligencia de negocios ya se sabe cómo debe de funcionar la empresa y un datawarehouse ayudaría a saber qué está pasando en la empresa ya sea en las transacciones que se hacen o en las quejas de los clientes ( si tiene call center). El datawarehouse ayudaría a la inteligencia de negocios a mostrarle los análisis e información que obtuvo y de qué decisiones podría tomar el encargado de tomar las decisiones en la empresa.

# Parte II del Parcial Consultas SQL 


En base al siguiente modelo relacional

cliente (id, nit, nombre, credito)
tienda (id, nombre, direccion)
compra (id, cliente_id, tienda_id, total, fecha)

Resuelvalos siguientes enunciados:

### a)Implemente el modelo relacional en SQLite. La base de datos debe de poseer datos de prueba y será utilizada por medio de Jupyter Notebooks  (10) Genere consulta SQL para generar / resolver 

### b)Nombres y créditos de clientes de los compradores de MAJADAS ordenado por crédito descendente y nombre ascendente.

### c)Agregar en el resultado anterior el crédito en dólares a un tipo decambio de 7.8.

### d)Parejas de clientes con el mismo crédito que no sean ellos mismos y que no haya parejas duplicadas

### e)Clientes que han comprado en MAJADAS y no en VH

### f)Todas las tiendas que tengan otras tiendas en la misma dirección

### g)Clientes con los créditos más altos (sin utilizar MAX())

### h)Clientes cuyo crédito en dólaressea mayor a 1 

### i)Personas que no han hecho ninguna compra

### j)Diferencia entre el promedio de crédito de los clientes de MAJADAS y de VH

### k)Número de clientes de cada tienda, de las que tienen compras, ordenado por nombre de tienda.

### l)Cree un trigger que considere apropiado para este esquema. Justifique su elección (5)

### m)Genere un reporte (vista) que muestre información de ventas a ser utilizado por los gerentes de la tienda.  El diseño (columnas y filtros) debe de ser justificado. (5)

### a)Implemente el modelo relacional en SQLite. La base de datos debe de poseer datos de prueba y será utilizada por medio de Jupyter Notebooks (10) Genere consulta SQL para generar / resolver

In [ ]:
%load_ext sql

Crear DB

In [2]:
%sql sqlite:///real34.db

'Connected: @real34.db'

###  Tabla Cliente GT

In [3]:
%%sql CREATE TABLE Cliente (
    cliente_id INTEGER PRIMARY KEY, 
    nit VARCHAR(150), 
    nombre VARCHAR(150),
    credito INTEGER)

 * sqlite:///real34.db
Done.

[]

In [4]:
import random
nombres = [ 'Jorge', 'Jenny', 'Aletse', 'Daniela', 'Yaneth', 'Juan', 'Josepino', 'Bidkar', 'Magda']
apellidos = [ 'Xetumul', 'Escobar', 'Kej', 'Martinez', 'Botran', 'Salmeri', 'Sartor', 'Melgar','Moscoso']
id = 0
for i in range(1000):
    id = i
    name = random.randint(0, len(nombres)-1)
    clienteid = name
    ape = random.randint(0, len(apellidos)-1)
    metal = (nombres[name] + ' ' + apellidos[ape])
    nombreid = random.randint(0, len(metal)-1)
    credito = round(random.uniform(100, 2000), 30)
    nitid= random.randint(10000000,99999999)
    


    
    %sql INSERT INTO Cliente VALUES ( :id, :nitid, :metal, :credito);

 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db

1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db

1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db

1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db

KeyboardInterrupt:

###  Tabla Tienda GT

In [7]:
%%sql CREATE TABLE Tienda (
    tienda_id INTEGER PRIMARY KEY, 
    nombre VARCHAR(150), 
    direccion VARCHAR(150))

 * sqlite:///real34.db
Done.

[]

In [9]:
import random
Tiendas = ['La FM Zacapa', 'Mega Plaza ', 'Majadas', 'VH', 'El Duende', 'El Salama' , 'Chile Cobanero', 'Humo En Tus Ojos']
direcciones= ['ZONA 1' , 'ZONA 2', 'ZONA 15', 'ZONA 16', 'ZONA 18', 'ZONA 12', 'GUALAN', 'LA UNION', 'PAJAPITA', 'COATEPEQUE','SOLOLA']

id = 0
for i in range(1000):
    id = i
    a = id
    dire= random.randint(0, len(direcciones)-1)
    full = (direcciones[dire] )
    
    tiendaid = random.randint(0, len(Tiendas)-1)
    
    
  
   
    
   
    
    %sql INSERT INTO Tienda VALUES ( :id, :a, :full);

 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db

1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db

1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db

1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db

KeyboardInterrupt:

###  Tabla Compras Compras GT

In [11]:
%%sql CREATE TABLE Compra (
    compras_id INTEGER PRIMARY KEY, 
    cliente_id INTEGER VARCHAR(50), 
    tienda_id VARCHAR(150),
    total INTEGER,
    fecha DATE,
    FOREIGN KEY (cliente_id) REFERENCES Cliente(id),
    FOREIGN KEY (tienda_id) REFERENCES Tienda(id))

 * sqlite:///real34.db
Done.

[]

In [12]:

    
    
import random
Tiendas = ['La FM Zacapa', 'Mega Plaza ', 'Majadas', 'VH', 'El Duende', 'El Salama' , 'Chile Cobanero', 'Humo En Tus Ojos']
direcciones= ['ZONA 1' , 'ZONA 2', 'ZONA 15', 'ZONA 16', 'ZONA 18', 'ZONA 12', 'GUALAN', 'LA UNION', 'PAJAPITA']
id = 0
for i in range(1000):
    id = i
    name = random.randint(0, len(nombres)-1)
    clienteid = name
    ape = random.randint(0, len(apellidos)-1)
    full = (nombres[name] + ' ' + apellidos[ape])
    tiendaid = random.randint(0, len(Tiendas)-1)
    total = round(random.uniform(100, 2000), 2)
    
   
    
    #esta parte ayuda a que se pueda ingresar la fecha a los comspras 
    day = random.randint(1, 30)
    month = random.randint(1, 12)
    year = random.randint(2006, 2019)
    date = (str(day)+'/'+str(month)+'/'+str(year))
    
    %sql INSERT INTO Compra VALUES ( :id, :clienteid, :tiendaid, :total, :date);

4
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db

1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db

1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db

1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
2
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
3
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
7
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
6
 * sqlite:///real34.db
1 rows affected.
5
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db
1 rows affected.
4
 * sqlite:///real34.db
1 rows affected.
0
 * sqlite:///real34.db
1 rows affected.
1
 * sqlite:///real34.db

KeyboardInterrupt:

   ### b)Nombres y créditos de clientes de los compradores de MAJADAS ordenado por crédito descendente y nombre ascendente.

In [20]:
%%sql select credito,nombre from Cliente
inner join Compra ON Cliente.cliente_id= Compra.cliente_id
where Compra.tienda_id=5
ORDER BY credito DESC, nombre ASC;

## compradores en tienda con id= 5 que seria majadas

 * sqlite:///real34.db
Done.

[(1913.065062861188, 'Jorge Martinez'),
 (1913.065062861188, 'Jorge Martinez'),
 (1913.065062861188, 'Jorge Martinez'),
 (1913.065062861188, 'Jorge Martinez'),
 (1913.065062861188, 'Jorge Martinez'),
 (1913.065062861188, 'Jorge Martinez'),
 (1913.065062861188, 'Jorge Martinez'),
 (1913.065062861188, 'Jorge Martinez'),
 (1913.065062861188, 'Jorge Martinez'),
 (1913.065062861188, 'Jorge Martinez'),
 (1913.065062861188, 'Jorge Martinez'),
 (1913.065062861188, 'Jorge Martinez'),
 (1852.8093103350147, 'Juan Xetumul'),
 (1852.8093103350147, 'Juan Xetumul'),
 (1852.8093103350147, 'Juan Xetumul'),
 (1852.8093103350147, 'Juan Xetumul'),
 (1852.8093103350147, 'Juan Xetumul'),
 (1852.8093103350147, 'Juan Xetumul'),
 (1852.8093103350147, 'Juan Xetumul'),
 (1852.8093103350147, 'Juan Xetumul'),
 (1554.1596393017696, 'Magda Salmeri'),
 (1554.1596393017696, 'Magda Salmeri'),
 (1554.1596393017696, 'Magda Salmeri'),
 (1554.1596393017696, 'Magda Salmeri'),
 (1554.1596393017696, 'Magda Salmeri'),
 (1554.1596393017696, 'Magda Salmeri'),
 (1554.1596393017696, 'Magda Salmeri'),
 (1554.1596393017696, 'Magda Salmeri'),
 (1554.1596393017696, 'Magda Salmeri'),
 (1554.1596393017696, 'Magda Salmeri'),
 (1554.1596393017696, 'Magda Salmeri'),
 (1554.1596393017696, 'Magda Salmeri'),
 (1554.1596393017696, 'Magda Salmeri'),
 (948.4123864997324, 'Josepino Botran'),
 (948.4123864997324, 'Josepino Botran'),
 (948.4123864997324, 'Josepino Botran'),
 (948.4123864997324, 'Josepino Botran'),
 (948.4123864997324, 'Josepino Botran'),
 (948.4123864997324, 'Josepino Botran'),
 (948.4123864997324, 'Josepino Botran'),
 (948.4123864997324, 'Josepino Botran'),
 (948.4123864997324, 'Josepino Botran'),
 (948.4123864997324, 'Josepino Botran'),
 (948.4123864997324, 'Josepino Botran'),
 (948.4123864997324, 'Josepino Botran'),
 (763.3617700804083, 'Daniela Kej'),
 (763.3617700804083, 'Daniela Kej'),
 (763.3617700804083, 'Daniela Kej'),
 (763.3617700804083, 'Daniela Kej'),
 (763.3617700804083, 'Daniela Kej'),
 (763.3617700804083, 'Daniela Kej'),
 (763.3617700804083, 'Daniela Kej'),
 (763.3617700804083, 'Daniela Kej'),
 (763.3617700804083, 'Daniela Kej'),
 (763.3617700804083, 'Daniela Kej'),
 (763.3617700804083, 'Daniela Kej'),
 (648.103566373715, 'Jorge Martinez'),
 (648.103566373715, 'Jorge Martinez'),
 (648.103566373715, 'Jorge Martinez'),
 (648.103566373715, 'Jorge Martinez'),
 (648.103566373715, 'Jorge Martinez'),
 (648.103566373715, 'Jorge Martinez'),
 (648.103566373715, 'Jorge Martinez'),
 (648.103566373715, 'Jorge Martinez'),
 (648.103566373715, 'Jorge Martinez'),
 (648.103566373715, 'Jorge Martinez'),
 (648.103566373715, 'Jorge Martinez'),
 (648.103566373715, 'Jorge Martinez'),
 (648.103566373715, 'Jorge Martinez'),
 (648.103566373715, 'Jorge Martinez'),
 (648.103566373715, 'Jorge Martinez'),
 (648.103566373715, 'Jorge Martinez'),
 (559.2058606007708, 'Aletse Escobar'),
 (559.2058606007708, 'Aletse Escobar'),
 (559.2058606007708, 'Aletse Escobar'),
 (559.2058606007708, 'Aletse Escobar'),
 (559.2058606007708, 'Aletse Escobar'),
 (559.2058606007708, 'Aletse Escobar'),
 (559.2058606007708, 'Aletse Escobar'),
 (559.2058606007708, 'Aletse Escobar'),
 (559.2058606007708, 'Aletse Escobar'),
 (482.2950634957399, 'Jenny Moscoso'),
 (482.2950634957399, 'Jenny Moscoso'),
 (482.2950634957399, 'Jenny Moscoso'),
 (482.2950634957399, 'Jenny Moscoso'),
 (482.2950634957399, 'Jenny Moscoso'),
 (482.2950634957399, 'Jenny Moscoso'),
 (217.93705318803063, 'Magda Kej'),
 (217.93705318803063, 'Magda Kej'),
 (217.93705318803063, 'Magda Kej'),
 (217.93705318803063, 'Magda Kej'),
 (217.93705318803063, 'Magda Kej'),
 (217.93705318803063, 'Magda Kej'),
 (217.93705318803063, 'Magda Kej')]

### c)Agregar en el resultado anterior el crédito en dólares a un tipo decambio de 7.8.

In [21]:
%%sql select (credito/7.8) as creditodolares, nombre from Cliente
inner join Compra ON Cliente.cliente_id= Compra.cliente_id
where Compra.tienda_id=5
ORDER BY credito DESC, nombre ASC;

 * sqlite:///real34.db
Done.

[(245.26475164887026, 'Jorge Martinez'),
 (245.26475164887026, 'Jorge Martinez'),
 (245.26475164887026, 'Jorge Martinez'),
 (245.26475164887026, 'Jorge Martinez'),
 (245.26475164887026, 'Jorge Martinez'),
 (245.26475164887026, 'Jorge Martinez'),
 (245.26475164887026, 'Jorge Martinez'),
 (245.26475164887026, 'Jorge Martinez'),
 (245.26475164887026, 'Jorge Martinez'),
 (245.26475164887026, 'Jorge Martinez'),
 (245.26475164887026, 'Jorge Martinez'),
 (245.26475164887026, 'Jorge Martinez'),
 (237.53965517115574, 'Juan Xetumul'),
 (237.53965517115574, 'Juan Xetumul'),
 (237.53965517115574, 'Juan Xetumul'),
 (237.53965517115574, 'Juan Xetumul'),
 (237.53965517115574, 'Juan Xetumul'),
 (237.53965517115574, 'Juan Xetumul'),
 (237.53965517115574, 'Juan Xetumul'),
 (237.53965517115574, 'Juan Xetumul'),
 (199.2512358079192, 'Magda Salmeri'),
 (199.2512358079192, 'Magda Salmeri'),
 (199.2512358079192, 'Magda Salmeri'),
 (199.2512358079192, 'Magda Salmeri'),
 (199.2512358079192, 'Magda Salmeri'),
 (199.2512358079192, 'Magda Salmeri'),
 (199.2512358079192, 'Magda Salmeri'),
 (199.2512358079192, 'Magda Salmeri'),
 (199.2512358079192, 'Magda Salmeri'),
 (199.2512358079192, 'Magda Salmeri'),
 (199.2512358079192, 'Magda Salmeri'),
 (199.2512358079192, 'Magda Salmeri'),
 (199.2512358079192, 'Magda Salmeri'),
 (121.59133160252979, 'Josepino Botran'),
 (121.59133160252979, 'Josepino Botran'),
 (121.59133160252979, 'Josepino Botran'),
 (121.59133160252979, 'Josepino Botran'),
 (121.59133160252979, 'Josepino Botran'),
 (121.59133160252979, 'Josepino Botran'),
 (121.59133160252979, 'Josepino Botran'),
 (121.59133160252979, 'Josepino Botran'),
 (121.59133160252979, 'Josepino Botran'),
 (121.59133160252979, 'Josepino Botran'),
 (121.59133160252979, 'Josepino Botran'),
 (121.59133160252979, 'Josepino Botran'),
 (97.86689360005235, 'Daniela Kej'),
 (97.86689360005235, 'Daniela Kej'),
 (97.86689360005235, 'Daniela Kej'),
 (97.86689360005235, 'Daniela Kej'),
 (97.86689360005235, 'Daniela Kej'),
 (97.86689360005235, 'Daniela Kej'),
 (97.86689360005235, 'Daniela Kej'),
 (97.86689360005235, 'Daniela Kej'),
 (97.86689360005235, 'Daniela Kej'),
 (97.86689360005235, 'Daniela Kej'),
 (97.86689360005235, 'Daniela Kej'),
 (83.09020081714296, 'Jorge Martinez'),
 (83.09020081714296, 'Jorge Martinez'),
 (83.09020081714296, 'Jorge Martinez'),
 (83.09020081714296, 'Jorge Martinez'),
 (83.09020081714296, 'Jorge Martinez'),
 (83.09020081714296, 'Jorge Martinez'),
 (83.09020081714296, 'Jorge Martinez'),
 (83.09020081714296, 'Jorge Martinez'),
 (83.09020081714296, 'Jorge Martinez'),
 (83.09020081714296, 'Jorge Martinez'),
 (83.09020081714296, 'Jorge Martinez'),
 (83.09020081714296, 'Jorge Martinez'),
 (83.09020081714296, 'Jorge Martinez'),
 (83.09020081714296, 'Jorge Martinez'),
 (83.09020081714296, 'Jorge Martinez'),
 (83.09020081714296, 'Jorge Martinez'),
 (71.69305905138089, 'Aletse Escobar'),
 (71.69305905138089, 'Aletse Escobar'),
 (71.69305905138089, 'Aletse Escobar'),
 (71.69305905138089, 'Aletse Escobar'),
 (71.69305905138089, 'Aletse Escobar'),
 (71.69305905138089, 'Aletse Escobar'),
 (71.69305905138089, 'Aletse Escobar'),
 (71.69305905138089, 'Aletse Escobar'),
 (71.69305905138089, 'Aletse Escobar'),
 (61.832700448171785, 'Jenny Moscoso'),
 (61.832700448171785, 'Jenny Moscoso'),
 (61.832700448171785, 'Jenny Moscoso'),
 (61.832700448171785, 'Jenny Moscoso'),
 (61.832700448171785, 'Jenny Moscoso'),
 (61.832700448171785, 'Jenny Moscoso'),
 (27.940647844619313, 'Magda Kej'),
 (27.940647844619313, 'Magda Kej'),
 (27.940647844619313, 'Magda Kej'),
 (27.940647844619313, 'Magda Kej'),
 (27.940647844619313, 'Magda Kej'),
 (27.940647844619313, 'Magda Kej'),
 (27.940647844619313, 'Magda Kej')]

### d)Parejas de clientes con el mismo crédito que no sean ellos mismos y que no haya parejas duplicadas

In [23]:
%sql INSERT INTO Cliente(cliente_id,nit,nombre,credito) VALUES(1231242141242112412,12312345534543543643,'z200 Escobar',100.8489430956789);

 * sqlite:///real34.db
1 rows affected.

[]

In [24]:
%%sql Select * from Cliente
where credito IN
(Select credito
From Cliente
Group by credito
having Count(credito) > 0
)
Order by credito
limit 3;

 * sqlite:///real34.db
Done.

[(1231242141242112412, '1.23123455345435e+19', 'z200 Escobar', 100.8489430956789),
 (581, '20620454', 'Aletse Martinez', 100.92830905761139),
 (592, '53024339', 'Daniela Botran', 104.34835756508816)]

In [26]:
### e)Clientes que han comprado en MAJADAS y no en VH
%%sql select credito, nombre from Cliente
inner join Compra ON Cliente.cliente_id= Compra.cliente_id
where Compra.tienda_id=5  Compra.tienda_id !=6
ORDER BY credito DESC, nombre ASC;

SyntaxError: invalid syntax (<ipython-input-26-b487388eddec>, line 3)

### f

In [37]:
##f)Todas las tiendas que tengan otras tiendas en la misma dirección

%sql INSERT INTO Tienda(tienda_id, nombre,direccion) VALUES(4000,4,'PAJAPITA');

%sql INSERT INTO Tienda(tienda_id, nombre,direccion) VALUES(4523434552353,4,'PAJAPITA');

 * sqlite:///real34.db
1 rows affected.

[]

### f)Todas las tiendas que tengan otras tiendas en la misma dirección¶

In [38]:
%%sql select *from Tienda 
WHERE direccion = 'PAJAPITA' AND nombre=4
limit 10;

 * sqlite:///real34.db
Done.

[(4000, '4', 'PAJAPITA'), (4523434552353, '4', 'PAJAPITA')]

### g)Clientes con los créditos más altos (sin utilizar MAX())

In [39]:
%%sql Select credito, nombre
from Cliente
order by credito desc
Limit 5;

 * sqlite:///real34.db
Done.

[(1999.275949027618, 'Yaneth Salmeri'),
 (1993.4909583570357, 'Yaneth Moscoso'),
 (1989.7342177462688, 'Bidkar Botran'),
 (1987.9386423617202, 'Juan Melgar'),
 (1985.9859930326154, 'Jorge Botran')]

### h)

In [40]:
%%sql Select (credito/7.8) as Credollar, nombre
from Cliente
where Credollar > 1
Limit 5;

 * sqlite:///real34.db
Done.

[(245.26475164887026, 'Jorge Martinez'),
 (83.09020081714296, 'Jorge Martinez'),
 (71.69305905138089, 'Aletse Escobar'),
 (199.2512358079192, 'Magda Salmeri'),
 (121.59133160252979, 'Josepino Botran')]

In [41]:
#i)Personas que no han hecho ninguna compra

#%sql Select * from Cliente Limit 10;

%sql INSERT INTO Cliente(cliente_id, nit, nombre, credito) Values( 7071996, 77777777777777777, 'Edward Elric', Null);

%sql Insert into Compra(compras_id,cliente_id,tienda_id,total,fecha) Values(777777777, 777777777777777, 888888888888888, 0, null);

 * sqlite:///real34.db
1 rows affected.
 * sqlite:///real34.db
1 rows affected.

[]

In [51]:
%%sql Select credito,nombre, Compra.compras_id, Compra.cliente_id, total from Cliente, Compra
WHERE total= 0;
    
### K Número de clientes de cada tienda, de las que tienen compras, ordenado por nombre de tienda

 * sqlite:///real34.db
Done.

[(1913.065062861188, 'Jorge Martinez', 777777777, 777777777777777, 0),
 (648.103566373715, 'Jorge Martinez', 777777777, 777777777777777, 0),
 (559.2058606007708, 'Aletse Escobar', 777777777, 777777777777777, 0),
 (1554.1596393017696, 'Magda Salmeri', 777777777, 777777777777777, 0),
 (948.4123864997324, 'Josepino Botran', 777777777, 777777777777777, 0),
 (763.3617700804083, 'Daniela Kej', 777777777, 777777777777777, 0),
 (217.93705318803063, 'Magda Kej', 777777777, 777777777777777, 0),
 (1852.8093103350147, 'Juan Xetumul', 777777777, 777777777777777, 0),
 (482.2950634957399, 'Jenny Moscoso', 777777777, 777777777777777, 0),
 (1188.035583587986, 'Yaneth Xetumul', 777777777, 777777777777777, 0),
 (1416.4054277039668, 'Bidkar Sartor', 777777777, 777777777777777, 0),
 (453.37578900941895, 'Daniela Botran', 777777777, 777777777777777, 0),
 (1985.9859930326154, 'Jorge Botran', 777777777, 777777777777777, 0),
 (1315.342563324058, 'Josepino Martinez', 777777777, 777777777777777, 0),
 (957.4571933070011, 'Yaneth Botran', 777777777, 777777777777777, 0),
 (1808.8712264909443, 'Yaneth Kej', 777777777, 777777777777777, 0),
 (518.7568544418648, 'Daniela Escobar', 777777777, 777777777777777, 0),
 (1179.5568398558792, 'Josepino Salmeri', 777777777, 777777777777777, 0),
 (1526.2505858600591, 'Aletse Martinez', 777777777, 777777777777777, 0),
 (1431.2996765510284, 'Daniela Moscoso', 777777777, 777777777777777, 0),
 (860.1920278701174, 'Bidkar Melgar', 777777777, 777777777777777, 0),
 (1395.0135683073524, 'Jenny Martinez', 777777777, 777777777777777, 0),
 (1119.7098057988815, 'Josepino Moscoso', 777777777, 777777777777777, 0),
 (1443.3014139997142, 'Jorge Melgar', 777777777, 777777777777777, 0),
 (1801.7002050355663, 'Josepino Botran', 777777777, 777777777777777, 0),
 (1079.9873441583468, 'Aletse Botran', 777777777, 777777777777777, 0),
 (338.58422411604363, 'Josepino Escobar', 777777777, 777777777777777, 0),
 (572.5248775365426, 'Bidkar Kej', 777777777, 777777777777777, 0),
 (1712.9533796296876, 'Yaneth Sartor', 777777777, 777777777777777, 0),
 (771.5528974953777, 'Jorge Kej', 777777777, 777777777777777, 0),
 (521.5688525197224, 'Aletse Escobar', 777777777, 777777777777777, 0),
 (1786.3015077883008, 'Juan Xetumul', 777777777, 777777777777777, 0),
 (1449.8283693515064, 'Juan Salmeri', 777777777, 777777777777777, 0),
 (1071.2196946576883, 'Bidkar Botran', 777777777, 777777777777777, 0),
 (1478.9340035823234, 'Juan Xetumul', 777777777, 777777777777777, 0),
 (516.0160795776108, 'Daniela Martinez', 777777777, 777777777777777, 0),
 (551.1065749787042, 'Juan Moscoso', 777777777, 777777777777777, 0),
 (1930.6488594403327, 'Juan Martinez', 777777777, 777777777777777, 0),
 (547.9410359683691, 'Yaneth Melgar', 777777777, 777777777777777, 0),
 (1764.1528119448287, 'Jorge Moscoso', 777777777, 777777777777777, 0),
 (1121.152246347936, 'Josepino Martinez', 777777777, 777777777777777, 0),
 (683.5247564342159, 'Aletse Escobar', 777777777, 777777777777777, 0),
 (293.11854077562805, 'Josepino Escobar', 777777777, 777777777777777, 0),
 (1715.1907587097458, 'Yaneth Kej', 777777777, 777777777777777, 0),
 (1768.8353387831035, 'Magda Escobar', 777777777, 777777777777777, 0),
 (909.3106024402333, 'Jorge Xetumul', 777777777, 777777777777777, 0),
 (152.24791605624839, 'Magda Botran', 777777777, 777777777777777, 0),
 (698.7084453634366, 'Magda Salmeri', 777777777, 777777777777777, 0),
 (1373.1277787320503, 'Magda Botran', 777777777, 777777777777777, 0),
 (1380.1444083436077, 'Bidkar Xetumul', 777777777, 777777777777777, 0),
 (481.02091500806074, 'Bidkar Moscoso', 777777777, 777777777777777, 0),
 (986.8512180775244, 'Yaneth Melgar', 777777777, 777777777777777, 0),
 (1441.219342585759, 'Jenny Melgar', 777777777, 777777777777777, 0),
 (1946.802389013633, 'Daniela Kej', 777777777, 777777777777777, 0),
 (421.4785285627527, 'Juan Xetumul', 777777777, 777777777777777, 0),
 (1446.1238324984222, 'Jorge Martinez', 777777777, 777777777777777, 0),
 (143.9944635340091, 'Magda Moscoso', 777777777, 777777777777777, 0),
 (1900.3341251336317, 'Aletse Martinez', 777777777, 777777777777777, 0),
 (937.652613346653, 'Juan Escobar', 777777777, 777777777777777, 0),
 (780.1379716751966, 'Jenny Martinez', 777777777, 777777777777777, 0),
 (1746.5393623730902, 'Jorge Sartor', 777777777, 777777777777777, 0),
 (867.4689366528337, 'Aletse Botran', 777777777, 777777777777777, 0),
 (416.5548142777904, 'Aletse Sartor', 777777777, 777777777777777, 0),
 (1183.8916545889756, 'Magda Melgar', 777777777, 777777777777777, 0),
 (346.97230785711315, 'Juan Moscoso', 777777777, 777777777777777, 0),
 (1500.1344467721376, 'Jorge Botran', 777777777, 777777777777777, 0),
 (1428.522437923657, 'Yaneth Martinez', 777777777, 777777777777777, 0),
 (1781.8476043861303, 'Yaneth Sartor', 777777777, 777777777777777, 0),
 (1805.2941120417738, 'Bidkar Sartor', 777777777, 777777777777777, 0),
 (1755.1299673221222, 'Jorge Martinez', 777777777, 777777777777777, 0),
 (820.9878637812529, 'Daniela Sartor', 777777777, 777777777777777, 0),
 (1642.1245482807183, 'Jorge Botran', 777777777, 777777777777777, 0),
 (1590.590046223565, 'Aletse Moscoso', 777777777, 777777777777777, 0),
 (1718.6906795147952, 'Josepino Salmeri', 777777777, 777777777777777, 0),
 (561.4107096337136, 'Juan Escobar', 777777777, 777777777777777, 0),
 (1388.5625574544945, 'Aletse Sartor', 777777777, 777777777777777, 0),
 (877.3071075277215, 'Daniela Salmeri', 777777777, 777777777777777, 0),
 (772.5970510848858, 'Jorge Kej', 777777777, 777777777777777, 0),
 (1771.7801727833507, 'Jenny Botran', 777777777, 777777777777777, 0),
 (1145.826077059427, 'Bidkar Sartor', 777777777, 777777777777777, 0),
 (1027.4621357113, 'Jenny Kej', 777777777, 777777777777777, 0),
 (299.2784898625297, 'Jenny Moscoso', 777777777, 777777777777777, 0),
 (509.7922858111109, 'Jorge Salmeri', 777777777, 777777777777777, 0),
 (276.70958240285984, 'Yaneth Escobar', 777777777, 777777777777777, 0),
 (309.68945164872423, 'Aletse Xetumul', 777777777, 777777777777777, 0),
 (1396.3674747069017, 'Daniela Moscoso', 777777777, 777777777777777, 0),
 (598.9633060190827, 'Daniela Melgar', 777777777, 777777777777777, 0),
 (213.96257297084298, 'Yaneth Xetumul', 777777777, 777777777777777, 0),
 (513.1088927399405, 'Yaneth Escobar', 777777777, 777777777777777, 0),
 (716.2339103267259, 'Daniela Escobar', 777777777, 777777777777777, 0),
 (1889.7386849646996, 'Josepino Salmeri', 777777777, 777777777777777, 0),
 (757.3753537231555, 'Yaneth Salmeri', 777777777, 777777777777777, 0),
 (1666.5558415733735, 'Jorge Martinez', 777777777, 777777777777777, 0),
 (1161.2037658544064, 'Magda Salmeri', 777777777, 777777777777777, 0),
 (1121.4331948876656, 'Josepino Escobar', 777777777, 777777777777777, 0),
 (1805.3264261847914, 'Jenny Botran', 777777777, 777777777777777, 0),
 (1423.0892857632969, 'Magda Xetumul', 777777777, 777777777777777, 0),
 (594.4600312505004, 'Bidkar Salmeri', 777777777, 777777777777777, 0),
 (1404.8582009552167, 'Yaneth Xetumul', 777777777, 777777777777777, 0),
 (736.6286757571278, 'Magda Kej', 777777777, 777777777777777, 0),
 (1526.2520721366654, 'Juan Martinez', 777777777, 777777777777777, 0),
 (250.89454557892196, 'Daniela Sartor', 777777777, 777777777777777, 0),
 (1196.840641367144, 'Jenny Sartor', 777777777, 777777777777777, 0),
 (1591.1669040154864, 'Jorge Salmeri', 777777777, 777777777777777, 0),
 (1565.1574218211863, 'Jenny Xetumul', 777777777, 777777777777777, 0),
 (1435.5640771365504, 'Josepino Moscoso', 777777777, 777777777777777, 0),
 (1591.5857321634358, 'Jenny Sartor', 777777777, 777777777777777, 0),
 (1861.9093743076728, 'Daniela Melgar', 777777777, 777777777777777, 0),
 (325.62730633178063, 'Magda Moscoso', 777777777, 777777777777777, 0),
 (502.5721869114349, 'Bidkar Xetumul', 777777777, 777777777777777, 0),
 (701.8392697871865, 'Daniela Sartor', 777777777, 777777777777777, 0),
 (1003.1289294910296, 'Juan Escobar', 777777777, 777777777777777, 0),
 (588.4779669858874, 'Magda Moscoso', 777777777, 777777777777777, 0),
 (1977.5680560268518, 'Bidkar Salmeri', 777777777, 777777777777777, 0),
 (1821.4754303793331, 'Juan Moscoso', 777777777, 777777777777777, 0),
 (958.6932092586712, 'Aletse Salmeri', 777777777, 777777777777777, 0),
 (254.63714626678288, 'Juan Salmeri', 777777777, 777777777777777, 0),
 (465.57712013099155, 'Yaneth Moscoso', 777777777, 777777777777777, 0),
 (186.59103341844832, 'Juan Kej', 777777777, 777777777777777, 0),
 (1125.2203012936045, 'Bidkar Melgar', 777777777, 777777777777777, 0),
 (1308.2823745708267, 'Jorge Botran', 777777777, 777777777777777, 0),
 (1073.225753645801, 'Jorge Escobar', 777777777, 777777777777777, 0),
 (1084.5100762145025, 'Daniela Botran', 777777777, 777777777777777, 0),
 (1023.7133567701007, 'Aletse Salmeri', 777777777, 777777777777777, 0),
 (1520.6749695917147, 'Yaneth Escobar', 777777777, 777777777777777, 0),
 (188.90025290425947, 'Magda Moscoso', 777777777, 777777777777777, 0),
 (377.83430120541016, 'Magda Xetumul', 777777777, 777777777777777, 0),
 (1297.9224963287684, 'Yaneth Martinez', 777777777, 777777777777777, 0),
 (424.26692465931376, 'Yaneth Xetumul', 777777777, 777777777777777, 0),
 (1074.6839032173543, 'Magda Xetumul', 777777777, 777777777777777, 0),
 (158.29877087390608, 'Magda Kej', 777777777, 777777777777777, 0),
 (429.44785339375557, 'Yaneth Escobar', 777777777, 777777777777777, 0),
 (582.3150573446594, 'Juan Escobar', 777777777, 777777777777777, 0),
 (1128.7701629827543, 'Josepino Melgar', 777777777, 777777777777777, 0),
 (307.64733848416626, 'Yaneth Moscoso', 777777777, 777777777777777, 0),
 (1285.0315040072699, 'Juan Escobar', 777777777, 777777777777777, 0),
 (498.92354290954216, 'Daniela Kej', 777777777, 777777777777777, 0),
 (197.4534384977922, 'Jorge Botran', 777777777, 777777777777777, 0),
 (105.14012374997719, 'Daniela Melgar', 777777777, 777777777777777, 0),
 (469.84711106838176, 'Josepino Sartor', 777777777, 777777777777777, 0),
 (1676.4177357465362, 'Jorge Salmeri', 777777777, 777777777777777, 0),
 (1255.0405509987606, 'Magda Moscoso', 777777777, 777777777777777, 0),
 (1189.310419344381, 'Juan Moscoso', 777777777, 777777777777777, 0),
 (1138.1373030215848, 'Jenny Xetumul', 777777777, 777777777777777, 0),
 (118.69827937337035, 'Aletse Martinez', 777777777, 777777777777777, 0),
 (113.34625226661925, 'Bidkar Kej', 777777777, 777777777777777, 0),
 (720.9269480341758, 'Jenny Salmeri', 777777777, 777777777777777, 0),
 (674.0599887690231, 'Yaneth Salmeri', 777777777, 777777777777777, 0),
 (1795.1119106841595, 'Jenny Escobar', 777777777, 777777777777777, 0),
 (461.16509784367247, 'Daniela Moscoso', 777777777, 777777777777777, 0),
 (381.32197492342425, 'Juan Melgar', 777777777, 777777777777777, 0),
 (1591.0659955929605, 'Aletse Botran', 777777777, 777777777777777, 0),
 (1485.6482607361984, 'Yaneth Kej', 777777777, 777777777777777, 0),
 (124.51633979426674, 'Jenny Moscoso', 777777777, 777777777777777, 0),
 (1263.3530252567712, 'Josepino Xetumul', 777777777, 777777777777777, 0),
 (1749.1272741291245, 'Magda Moscoso', 777777777, 777777777777777, 0),
 (1956.8633817407344, 'Bidkar Moscoso', 777777777, 777777777777777, 0),
 (934.1781505197499, 'Bidkar Martinez', 777777777, 777777777777777, 0),
 (188.56120578364454, 'Aletse Melgar', 777777777, 777777777777777, 0),
 (750.4131120542319, 'Bidkar Botran', 777777777, 777777777777777, 0),
 (1062.279142456559, 'Jorge Escobar', 777777777, 777777777777777, 0),
 (207.5146818124064, 'Jorge Kej', 777777777, 777777777777777, 0),
 (1554.3701936194634, 'Juan Martinez', 777777777, 777777777777777, 0),
 (119.8301851584261, 'Aletse Salmeri', 777777777, 777777777777777, 0),
 (750.1339176865116, 'Yaneth Xetumul', 777777777, 777777777777777, 0),
 (1743.6222970661338, 'Daniela Martinez', 777777777, 777777777777777, 0),
 (1213.388564267779, 'Jenny Sartor', 777777777, 777777777777777, 0),
 (1794.1573606914485, 'Josepino Moscoso', 777777777, 777777777777777, 0),
 (293.474766518362, 'Josepino Martinez', 777777777, 777777777777777, 0),
 (418.7883990967117, 'Magda Sartor', 777777777, 777777777777777, 0),
 (796.3796214449965, 'Jorge Kej', 777777777, 777777777777777, 0),
 (1258.067837410698, 'Bidkar Martinez', 777777777, 777777777777777, 0),
 (612.041639992658, 'Juan Escobar', 777777777, 777777777777777, 0),
 (501.1830819699419, 'Yaneth Botran', 777777777, 777777777777777, 0),
 (1540.4714648629365, 'Yaneth Salmeri', 777777777, 777777777777777, 0),
 (623.7289647098286, 'Bidkar Martinez', 777777777, 777777777777777, 0),
 (192.56482911425144, 'Josepino Martinez', 777777777, 777777777777777, 0),
 (1196.851145577711, 'Yaneth Martinez', 777777777, 777777777777777, 0),
 (1738.0963793930318, 'Yaneth Botran', 777777777, 777777777777777, 0),
 (1033.9343381195176, 'Bidkar Escobar', 777777777, 777777777777777, 0),
 (1667.4821800241289, 'Bidkar Kej', 777777777, 777777777777777, 0),
 (600.0948364067276, 'Josepino Botran', 777777777, 777777777777777, 0),
 (1630.6143739172396, 'Magda Sartor', 777777777, 777777777777777, 0),
 (589.6575722572065, 'Jorge Sartor', 777777777, 777777777777777, 0),
 (548.3757670817729, 'Juan Escobar', 777777777, 777777777777777, 0),
 (399.2688533940175, 'Bidkar Sartor', 777777777, 777777777777777, 0),
 (1021.3626907119992, 'Daniela Botran', 777777777, 777777777777777, 0),
 (841.8274166664378, 'Josepino Sartor', 777777777, 777777777777777, 0),
 (1675.3249884218678, 'Jorge Salmeri', 777777777, 777777777777777, 0),
 (1173.6029917459368, 'Juan Melgar', 777777777, 777777777777777, 0),
 (405.55852259605507, 'Juan Sartor', 777777777, 777777777777777, 0),
 (128.37414476938324, 'Yaneth Kej', 777777777, 777777777777777, 0),
 (1381.5160974756095, 'Aletse Escobar', 777777777, 777777777777777, 0),
 (975.2332265894034, 'Magda Sartor', 777777777, 777777777777777, 0),
 (608.4641716097658, 'Aletse Botran', 777777777, 777777777777777, 0),
 (202.19276651658953, 'Daniela Botran', 777777777, 777777777777777, 0),
 (226.06290450736168, 'Daniela Xetumul', 777777777, 777777777777777, 0),
 (154.15437596812149, 'Aletse Moscoso', 777777777, 777777777777777, 0),
 (1473.1509120433766, 'Daniela Melgar', 777777777, 777777777777777, 0),
 (1208.6571670023047, 'Aletse Botran', 777777777, 777777777777777, 0),
 (1629.7134847474017, 'Magda Martinez', 777777777, 777777777777777, 0),
 (563.7518668854223, 'Bidkar Martinez', 777777777, 777777777777777, 0),
 (1528.8367561608832, 'Magda Kej', 777777777, 777777777777777, 0),
 (668.4817702497962, 'Jenny Botran', 777777777, 777777777777777, 0),
 (1268.4503168413291, 'Josepino Escobar', 777777777, 777777777777777, 0),
 (1108.0599248800459, 'Josepino Martinez', 777777777, 777777777777777, 0),
 (776.5524314021136, 'Daniela Melgar', 777777777, 777777777777777, 0),
 (1699.6629282865088, 'Yaneth Moscoso', 777777777, 777777777777777, 0),
 (310.1418617676311, 'Bidkar Moscoso', 777777777, 777777777777777, 0),
 (1227.6663316340912, 'Daniela Melgar', 777777777, 777777777777777, 0),
 (375.41377289391863, 'Bidkar Salmeri', 777777777, 777777777777777, 0),
 (1223.1829807085674, 'Daniela Sartor', 777777777, 777777777777777, 0),
 (1642.2540468491009, 'Bidkar Botran', 777777777, 777777777777777, 0),
 (1475.4090037936394, 'Juan Escobar', 777777777, 777777777777777, 0),
 (1909.878166584733, 'Josepino Botran', 777777777, 777777777777777, 0),
 (337.3726264611104, 'Yaneth Botran', 777777777, 777777777777777, 0),
 (1355.410331397487, 'Bidkar Xetumul', 777777777, 777777777777777, 0),
 (1570.079066651934, 'Josepino Xetumul', 777777777, 777777777777777, 0),
 (1148.7686893741406, 'Daniela Xetumul', 777777777, 777777777777777, 0),
 (636.6988577227617, 'Daniela Escobar', 777777777, 777777777777777, 0),
 (229.31464528656832, 'Juan Martinez', 777777777, 777777777777777, 0),
 (526.6912546066467, 'Jorge Botran', 777777777, 777777777777777, 0),
 (1217.1879601918258, 'Bidkar Moscoso', 777777777, 777777777777777, 0),
 (1326.426867343839, 'Jorge Escobar', 777777777, 777777777777777, 0),
 (1618.50117838955, 'Juan Martinez', 777777777, 777777777777777, 0),
 (1566.4140081918476, 'Aletse Martinez', 777777777, 777777777777777, 0),
 (409.12419877113734, 'Daniela Moscoso', 777777777, 777777777777777, 0),
 (520.6543900924105, 'Juan Melgar', 777777777, 777777777777777, 0),
 (175.50441136800768, 'Aletse Salmeri', 777777777, 777777777777777, 0),
 (1615.546468979584, 'Josepino Melgar', 777777777, 777777777777777, 0),
 (1744.7004581130507, 'Juan Botran', 777777777, 777777777777777, 0),
 (919.1947426111274, 'Daniela Kej', 777777777, 777777777777777, 0),
 (1374.5937439151555, 'Bidkar Melgar', 777777777, 777777777777777, 0),
 (532.6828732156155, 'Yaneth Salmeri', 777777777, 777777777777777, 0),
 (1576.997802749586, 'Aletse Xetumul', 777777777, 777777777777777, 0),
 (144.69306555797448, 'Magda Salmeri', 777777777, 777777777777777, 0),
 (398.57808401940235, 'Magda Escobar', 777777777, 777777777777777, 0),
 (1767.1178128596487, 'Yaneth Botran', 777777777, 777777777777777, 0),
 (1665.6059942738907, 'Josepino Xetumul', 777777777, 777777777777777, 0),
 (139.93370994625616, 'Magda Kej', 777777777, 777777777777777, 0),
 (1908.8496596013533, 'Yaneth Moscoso', 777777777, 777777777777777, 0),
 (1442.988736940301, 'Juan Salmeri', 777777777, 777777777777777, 0),
 (310.0912219332689, 'Aletse Xetumul', 777777777, 777777777777777, 0),
 (178.64953364856893, 'Daniela Kej', 777777777, 777777777777777, 0),
 (613.1543867743661, 'Jenny Kej', 777777777, 777777777777777, 0),
 (1155.9948433725626, 'Jenny Escobar', 777777777, 777777777777777, 0),
 (725.8683823256487, 'Jenny Xetumul', 777777777, 777777777777777, 0),
 (996.2557185086644, 'Yaneth Escobar', 777777777, 777777777777777, 0),
 (709.1664251165531, 'Bidkar Martinez', 777777777, 777777777777777, 0),
 (1484.3871683120803, 'Aletse Melgar', 777777777, 777777777777777, 0),
 (1262.8559968118832, 'Bidkar Kej', 777777777, 777777777777777, 0),
 (1529.4075041920398, 'Bidkar Salmeri', 777777777, 777777777777777, 0),
 (553.7187007749194, 'Jenny Moscoso', 777777777, 777777777777777, 0),
 (1089.7486912003685, 'Josepino Kej', 777777777, 777777777777777, 0),
 (1873.3512715839854, 'Jenny Moscoso', 777777777, 777777777777777, 0),
 (1130.9528953470785, 'Juan Salmeri', 777777777, 777777777777777, 0),
 (411.3989504616226, 'Daniela Melgar', 777777777, 777777777777777, 0),
 (603.9119066524563, 'Yaneth Xetumul', 777777777, 777777777777777, 0),
 (334.1136110735782, 'Magda Martinez', 777777777, 777777777777777, 0),
 (1751.9200847633235, 'Josepino Xetumul', 777777777, 777777777777777, 0),
 (200.78350149923696, 'Yaneth Martinez', 777777777, 777777777777777, 0),
 (1999.275949027618, 'Yaneth Salmeri', 777777777, 777777777777777, 0),
 (1965.6493144774279, 'Juan Salmeri', 777777777, 777777777777777, 0),
 (755.3948160780825, 'Jorge Botran', 777777777, 777777777777777, 0),
 (1317.1413036456863, 'Jorge Botran', 777777777, 777777777777777, 0),
 (1227.5931021396693, 'Juan Sartor', 777777777, 777777777777777, 0),
 (1751.8614501969478, 'Jenny Kej', 777777777, 777777777777777, 0),
 (159.3486596818033, 'Daniela Xetumul', 777777777, 777777777777777, 0),
 (1831.7017846863469, 'Juan Salmeri', 777777777, 777777777777777, 0),
 (381.5684989280432, 'Juan Escobar', 777777777, 777777777777777, 0),
 (1406.8218938819787, 'Josepino Escobar', 777777777, 777777777777777, 0),
 (1311.559006619742, 'Bidkar Moscoso', 777777777, 777777777777777, 0),
 (1052.3036481974596, 'Magda Kej', 777777777, 777777777777777, 0),
 (1431.7111928269082, 'Yaneth Sartor', 777777777, 777777777777777, 0),
 (1705.1054129962658, 'Juan Moscoso', 777777777, 777777777777777, 0),
 (337.6136458376163, 'Jorge Botran', 777777777, 777777777777777, 0),
 (1536.6099568617853, 'Jorge Escobar', 777777777, 777777777777777, 0),
 (1865.4310399692567, 'Juan Escobar', 777777777, 777777777777777, 0),
 (520.666832132361, 'Daniela Botran', 777777777, 777777777777777, 0),
 (1434.8273310009458, 'Josepino Kej', 777777777, 777777777777777, 0),
 (796.2679007608276, 'Jorge Kej', 777777777, 777777777777777, 0),
 (1240.7288029217036, 'Jenny Salmeri', 777777777, 777777777777777, 0),

In [52]:
###  l)Cree un trigger que considere apropiado para este esquema. Justifique su elección (5)

%%sql CREATE TRIGGER MAYUSNOMBRE
    ON Cliente
    AFTER INSERT, UPDATE
AS
BEGIN

    UPDATE Cliente
    SET nombre= Upper(nombre)
    where cliente_id IN(SELECT cliente_id FROM Cliente)
end;

IndentationError: unexpected indent (<ipython-input-52-5f3023f39ba0>, line 4)